### ISSUE TITLE
pthreads usage prevents building with msvc

### ISSUE THREAD

**Issue by learn-more** [LiamBindle/MQTT-C#105]
In the bio_publisher and openssl_publisher there is some code that uses pthreads for threading (and usleep/sleep).
To make this build / work in msvc, there should be additional code replacing this usage with windows-specific threading functions.
What would be the preferred way to handle this?

1. Add #ifdef(_WIN32) around the pthreads / windows specific functions
2. Create a copy of the bio_publisher.c / openssl_publisher.c with windows specific stuff
3. Create a (pal-like) header to handle this abstraction
4. Other?

**Comment by LiamBindle** [comment]
Hi Mark. My vote would go towards (2) because I think it would simpler/easier for new users (they would probably only look at the platform-specific file for their platform), but I'll defer to whatever you think is best.

**Comment by LiamBindle** [comment]
Fixed in #108
