### ISSUE TITLE
Automatic reconnect

### ISSUE THREAD

**Issue by LiamBindle** [LiamBindle/MQTT-C#11]
Supporting the auto-reconnecting feature that some other MQTT libraries support would be a good enhancement. I'm not yet familiar with this feature, but it was requested by @jedidiahuang.

I'm not going to have time to add this right away, but I wanted to submit this issue to start a discussion/take note that its something that would be good to add. 

If anyone has any comments/suggestion feel free to include them in this thread.

**Comment by jedidiahuang** [comment]
Hi Liam,

I found error compiling of the example reconnect_subscriber.c

Best Regards,
Jedidiah

**Comment by LiamBindle** [comment]
Hi Jedidiah,

Hmm, I wasn't expecting that; I'm able to compile it on my home and work computers. Could you include the compiler errors that you are seeing?

Regards,

Liam

**Comment by jedidiahuang** [comment]
Hi Liam,
I'd just downloaded reconnect_subscriber.c and compile it:
Compile Error messages are as following:
```
reconnect_subscriber.c: In function '`reconnect_client`':
reconnect_subscriber.c:135:26: error: '`MQTT_ERROR_INITIAL_RECONNECT`' **undeclared** (first use in this function)
    ` if (client->error != **MQTT_ERROR_INITIAL_RECONNECT) {**`
                          ^
reconnect_subscriber.c:135:26: note: each undeclared identifier is reported only once for each function it appears in
```

**Comment by jedidiahuang** [comment]
Hi Liam,

I think you didn't add **mqtt_reinit()** and **mqtt_init_reconnect()** function into mqtt.c
Following error message were ld error:
```
/tmp/ccNDau5n.o: In function `reconnect_client':
reconnect_subscriber.c:(.text+0xbe): undefined reference to `**mqtt_reinit**'
/tmp/ccNDau5n.o: In function `main':
reconnect_subscriber.c:(.text.startup+0x58): undefined reference to `**mqtt_init_reconnect**'

```

**Comment by LiamBindle** [comment]
Hi Jedidiahuang,

Hmm, I'm not sure why that would be happening. To me, it looks like you are not using the most recent `mqtt.c` from the [reconnect branch](https://github.com/LiamBindle/MQTT-C/blob/reconnect/). Is this possible?

On the reconnect branch you will find `mqtt_reinit` on line 132:
https://github.com/LiamBindle/MQTT-C/blob/e052e97224a299153e37fd751bd66a77a951ccea/src/mqtt.c#L132-L146

and `mqtt_init_reconnect` on line 103:
https://github.com/LiamBindle/MQTT-C/blob/e052e97224a299153e37fd751bd66a77a951ccea/src/mqtt.c#L103-L130

Can you see both of these functions in your `mqtt.c`?

**Comment by jedidiahuang** [comment]
Hi Liam

About detecting TCP socket connection is broken and reconnect a new socket is not easy. 
Your reconnection_subscriber.c example inject an MQTT_ERROR_SOCKET_ERROR by setting it to client.error  instead of physically unplug LAN cable for few seconds, you'll not see the truth.
I don't think you've solved reconnection issue, it won't work in real world.
Furthermore, since you use a buffer for publishing and subscribing and create a refresh thread for flushing socket I/O, once TCP connection is broken, it will lost many data queued in buffer.

Best Regards,
Jedidiah

**Comment by LiamBindle** [comment]
Hi Jedidiah,

Sorry for the delay in responding, I missed your comment.

I understand your concerns, but I think we have different ideas about the purpose of this enhancement. My intention with this enhancement is to provide a simple and clean way to reconnect a client to the broker after the client has gone into an error state (before this you had to fully destroy the client and reinitialize everything from the start). With this enhancement, the user has complete control over error handling, reinitializing the client, and reconfiguring the connection without interrupting the normal flow of their program (since the reconnection is done internally by calling the user-defined `reconnect_callback` in `mqtt_sync()`). The purpose of [reconnect_subscriber.c](https://github.com/LiamBindle/MQTT-C/blob/master/examples/reconnect_subscriber.c) is simply to demonstrate recovering the connection from an error state without interrupting the normal flow of the program.

With regards to your application, I think this latest merge (74da7af) will be helpful. I have added an additional callback, `inspector_callback` to `struct mqtt_client`. This callback is called on every call to `mqtt_sync()` and allows the user to perform their own error checking and socket inspections. If the user deems it necessary they can put the client into an error state my setting `client->error`.

To implement the Ethernet unplug event you will need to define an inspector function like so:
```c
enum MQTTErrors inspector_callback(struct mqtt_client* client) {
    int socketfd = client->socketfd;
    int is_error = 0;

    /* inspect socketfd as you'd like below */
    ...

    /* put the client in error if necessary */
    if (is_error) {
        client->error = MQTT_ERROR_SOCKET_ERROR;
        return MQTT_ERROR_SOCKET_ERROR;
    }
    return MQTT_OK;
}
```

Then, whenever your `inspector_callback` puts the client into an error state your `reconnect_callback` will be called (which will reestablish the connection). 

Recovering the contents of your send buffer can be done by looping through the client's message queue and re-registering the message via `mqtt_mq_register` (this could be put in your reconnect callback). This would look something like so
```c
void reconnect_callback(struct mqtt_client* client) {
    /* error handling as you'd do normally */
    ...

    /* save the old message queue */
    mqtt_message_queue old_mq_copy;
    memcpy(&old_mq_copy, &client->mq, sizeof(struct mqtt_message_queue));

    /* close/open the socket  */
    ... 

    /* reinitialize the client and connect */
    mqtt_reinit(...);
    mqtt_connect(...);

    /* recover the old message queues contents */
    for(int i = 0; i < mqtt_mq_length(&old_mq_copy); ++i) {
        struct mqtt_queued_message* msg = mqtt_mq_get(&old_mq_copy, i);
        if (/* inspect msg to see determine if it should be re-registerd */) {
            struct mqtt_queued_message* reregistered = mqtt_mq_register(&client->mq, msg->size);
            /* copy properties of msg into reregistered */
        }
    }
}
```

Refer to the details section for documentation on working with the message queue. 

Let me know if theres anything I can help you with,

Liam

**Comment by LiamBindle** [comment]
I'm going to close this issue because I think that it's resolved with 74da7af, but feel free to reopen or submit more enhancement issues if you would like. 

Best regards,

Liam

**Comment by trustefda** [comment]
I have implemented the automatic reconnect with the functions mqtt_init_reconnect and mqtt_reinit as well as the callback. Is not there a problem with the messages with QoS Level 1 or 2 because the message qeueue gets cleaned up? After all, according to the MQTT standard, the messages with the QoS level 1 or 2 that have not yet been confirmed should be transmitted again as soon as the connection is back.

Best regards,
Stefan

**Comment by LiamBindle** [comment]
Hi Stefan,

Yeah, I think you are right. Section 4.4 of the [MQTT v3.1.1 standard](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/csprd02/mqtt-v3.1.1-csprd02.html#_Toc385349834) says that the client should properly re-send any unacknowledged packets. Currently, MQTT-C clears the entire state of the client upon `mqtt_reinit` (the implementation of `mqtt_reinit` is quite simple).

Do you see this as a problem? 

Liam

**Comment by trustefda** [comment]
Hi Liam,

currently it is not a problem. But maybe it will get relevant.

But I think that you get solved by deleting only the messages with the QoS level 0 from the message queue. And as long as you have no connection, the message queue will not be processed. The Connect Packet must then be sent immediately and not queued in the message queue.
