### ISSUE TITLE
can not compile by mingw

### ISSUE THREAD

**Issue by cl2006ky** [LiamBindle/MQTT-C#115]
In file included from include/mqtt.h:43:0,                                                                                                                                                                         from communication_management.c:21:                                                                                                                                              include/mqtt_pal.h:161:26: error: unknown type name 'mqtt_pal_socket_handle'                                                                                                                       ssize_t mqtt_pal_sendall(mqtt_pal_socket_handle fd, const void* buf, size_t len, int flags);                                                                                                                               ^                                                                                                                                                                       include/mqtt_pal.h:174:26: error: unknown type name 'mqtt_pal_socket_handle'                                                                                                                       ssize_t mqtt_pal_recvall(mqtt_pal_socket_handle fd, void* buf, size_t bufsz, int flags);                                                                                                                                   ^                                                                                                                                                                       In file included from communication_management.c:21:0:                                                                                                                                            include/mqtt.h:946:5: error: unknown type name 'mqtt_pal_time_t'                                                                                                                                       mqtt_pal_time_t time_sent;                                                                                                                                                                        ^                                                                                                                                                                                            In file included from communication_management.c:21:0:                                                                                                                                            include/mqtt.h:1095:5: error: unknown type name 'mqtt_pal_socket_handle'                                                                                                                               mqtt_pal_socket_handle socketfd;                                                                                                                                                                  ^                                                                                                                                                                                            include/mqtt.h:1123:5: error: unknown type name 'mqtt_pal_time_t'                                                                                                                                      mqtt_pal_time_t time_of_last_send;                                                                                                                                                                ^                                                                                                                                                                                            include/mqtt.h:1232:5: error: unknown type name 'mqtt_pal_mutex_t'                                                                                                                                     mqtt_pal_mutex_t mutex;                                                                                                                                                                           ^                                                                                                                                                                                            include/mqtt.h:1348:27: error: unknown type name 'mqtt_pal_socket_handle'                                                                                                                                                    mqtt_pal_socket_handle sockfd,                                                                                                                                                                    ^                                                                                                                                                                      include/mqtt.h:1425:18: error: unknown type name 'mqtt_pal_socket_handle'                                                                                                                                           mqtt_pal_socket_handle socketfd,                                                                                                                                                                  ^                                                                                                                                                                               cc1.exe: warning: unrecognized command line option '-Wno-duplicate-decl-specifier-c'                                                                                                              make: *** [communication_management.o] ▒▒▒▒ 1
--

**Comment by LiamBindle** [comment]
@cl2006ky Do you need MinGW? MQTT-C works on Windows. If you do need to use MinGW, I believe `#include <stdint.h>` might help you out but it will take a little bit of troubleshooting.

See also: https://github.com/LiamBindle/MQTT-C/issues/99#issuecomment-669324575
