### ISSUE TITLE
wolfSSL support?

### ISSUE THREAD

**Issue by xiongyu0523** [LiamBindle/MQTT-C#117]
support wolfssl in pal? I have a project currently running MQTT-C on top of wolfSSL, it work well with mosquitto not sure if it covers all exceptional cases include server side termination etc. Would you please take a look to see if open for a PR. thanks

https://github.com/xiongyu0523/azure-sphere-mqtts/blob/master/MQTT-C/src/mqtt_pal.c

**Comment by LiamBindle** [comment]
@xiongyu0523 Thanks for writing. I'd be happy to merge a PR adding WolfSSL to the PAL. Could you make a PR?

**Comment by xiongyu0523** [comment]
PR issued, please link with https://github.com/LiamBindle/MQTT-C/pull/118

**Comment by LiamBindle** [comment]
Thanks @xiongyu0523!
