### ISSUE TITLE
How to set connect_flags?

### ISSUE THREAD

**Issue by jedidiahuang** [LiamBindle/MQTT-C#12]
Hi Liam, 

I've applied your update. It works well now.
Would you mind to explain how to set connect_flags while calling mqtt_connect()?
For example, I want to inform broker to clean_session when connected
Thanks a lot

Best Regards, 
Jedidiahuang

**Comment by LiamBindle** [comment]
Yeah, no problem. The 8th argument to `mqtt_connect` are the connect flags. These flags are enumerated in `enum MQTTConnectFlags` on line 587 of `mqtt.h`.

https://github.com/LiamBindle/MQTT-C/blob/dc96097d683bd6ef773c1fd89b540d1f895e2610/include/mqtt.h#L587-L597

For example, if you want to set "clean session" you would pass `MQTT_CONNECT_CLEAN_SESSION` as the 8th argument to `mqtt_connect`.

If you want to set multiple flags, for example, "clean session" and a will with QoS level 2, you would pass `MQTT_CONNECT_CLEAN_SESSION | MQTT_CONNECT_WILL | MQTT_CONNECT_WILL_QOS_2`.

---

It should be noted that the following flags are the only flags that need to be set explicitly:
- `MQTT_CONNECT_CLEAN_SESSION`
- `MQTT_CONNECT_WILL_QOS_X`
- `MQTT_CONNECT_WILL_RETAIN`

All the other flags are automatically determined based on the arguments to `mqtt_connect` (for example if the `user_name` argument is not `NULL` then MQTT-C will automatically set `MQTT_CONNECT_USER_NAME`). This means that in the multi-flag example given above the `MQTT_CONNECT_WILL` is not mandatory as is automatically set when `will_topic` and `will_message` are not `NULL`.
