### ISSUE TITLE
planned support for mqtt v5?

### ISSUE THREAD

**Issue by oyvindaakre** [LiamBindle/MQTT-C#122]
Great work, guys!
My question: Are there plans to support mqtt v5?

**Comment by LiamBindle** [comment]
Hi @oyvindaakre, I don't think it would be a large undertaking, but I haven't heard of anyone that wants to take it on (see https://github.com/LiamBindle/MQTT-C/issues/20).

If you or anyone else wants to implement version 5, I'd be happy to merge it.

**Comment by oyvindaakre** [comment]
Ok, thanks for the prompt response :) If I'm able I'll let you know :)
