### ISSUE TITLE
MQTT_ERROR_SEND_BUFFER_IS_FULL not cleared.

### ISSUE THREAD

**Issue by truhann** [LiamBindle/MQTT-C#124]
Good day,

I found, what I believe, is a possible bug.

Description:
Once more messages, that can fit in the send buffer, are pushed to the send buffer via mqtt_publish the MQTT_ERROR_SEND_BUFFER_IS_FULL error flag is set.  This flag is not cleared after the send buffer has been purged.

Work around:
The work around I implemented was to clear this flag in __mqtt_send after the mqtt_pal_sendall call, but I don't think this is a proper fix.  It will most probably only work for qos 0.  I guess the place to fix it is somewhere in MQTT_CLIENT_TRY_PACK after the mqtt_mq_clean.

<edit>
OK, I did further reading in the closed issues and saw issue #7 . 
I don't want to use the auto reconnect feature since my platform needs to share a single socket between different modules.  I don't view the SEND_BUFFER_IS_FULL as an error state, so I don't want to disconnect/reconnect.  My use case is that I need to push a local log to the broker as fast as possible with limited resources.  So by pushing messages via mqtt_publish until SEND_BUFFER_IS_FULL is returned nicely optimise resource usage.  The only issue is that in this case, it looks as if the SEND_BUFFER_IS_FULL error is not cleared after the send buffer was purged.

Regards
Truhann

**Comment by LiamBindle** [comment]
Hi @truhann, sorry for the slow response. The root issue here that has blocked a solution thus far is this: if the send buffer is full, how can we handle ingress QoS 1 and 2 background messages without allocating memory. I'd be very happy to merge a PR that can solve this problem.

An alternative option that comes to mind would be adding a set of "behaviour" flags to the `mqtt_client` structure. These flags could be enabled to turn on certain feature/behaviour, such as `client->flags->RECOVER_FROM_SEND_BUFFER_IS_FULL`.
