### ISSUE TITLE
Enhancement suggestion - Full purge of send buffer

### ISSUE THREAD

**Issue by truhann** [LiamBindle/MQTT-C#125]
Hello,

The current __mqtt_send forward each individual mqtt message separately to the mqtt_pal_sendall bearer. 

The shortcoming of this is that on platforms where the mqtt_pal_sendall call has got a high latency (i.e. it blocks and only returns when the acknowledgment has been received that data arrived at the broker) it causes high latency communication.   This is especially true with bearers like cellular (2G, CAT-M/NB-IoT) are used.

Any chance this module can be refactored in order to purge all the messages in the send queue simultaneously in a single mqtt_pal_sendall call?

Thanks
Truhann

**Comment by LiamBindle** [comment]
@truhann, I'd be open to a mechanism for this via something like the behaviour flags I suggested in #124. This specific behaviour would only work if the user was exclusively sending/recieving QoS 0 messages.
