### ISSUE TITLE
publish and Network packet relation

### ISSUE THREAD

**Issue by fabulously** [LiamBindle/MQTT-C#132]
Test program I use publish data at every program loop cycle.  And use sample code pthread_create()  to perform client_refresher(). (like reconnect_subscriber.c )

I record the publish data and  mqtt_sync() timing. And I use the software wireshark to monitoring Network packet.

I have two question as follows:

1.Could each MQTT publish data  use  each Network packet ? 

2. Is mqtt_sync() perform stand for publish data send out by Network packet?

**Comment by LiamBindle** [comment]
Hi @fabulously, thanks for writing. 

> 1.Could each MQTT publish data use each Network packet ?
I'm not quite sure what you mean. Every time you publish data it will be sent over the network, but the exact way that happens is controlled by your socket library. I suspect if you tried to send a very large message, it would be broken up into multiple packets, but if you publish messages are small, I suspect they are contained in a single packet. That's just my guess though---I'm not an expert on this stuff.

> 2. Is mqtt_sync() perform stand for publish data send out by Network packet?

`mqtt_sync()` is essentially like "run the MQTT-C backend". That includes publishing packets, recieving packets, and handling other types of packets like keep-alive pings to the broker, and behind-the-scenes QoS messages.

**Comment by fabulously** [comment]
Thanks for your reply. 
1.  You are right. The library is control publish data to transfer Network packets .  It is use mqtt_pal_sendall() function.  As you said, the small publish data could be contained in a single Network packet. 
2.  I see the library.  I am realize what you meaning.   Thank you your kindness.
