### ISSUE TITLE
How To Konwn NetWork Disconnect?

### ISSUE THREAD

**Issue by buutuud** [LiamBindle/MQTT-C#17]
Hi, There is no callback,get me network disconnect? if i want to known how to do that?

**Comment by LiamBindle** [comment]
Hi,

Inspecting the state of the underlying socket can be accomplished using the `inspector_callback` member in your `mqtt_client`. You need to define a function that looks like the following.
```c
enum MQTTErrors my_socket_inspector(struct mqtt_client* client) {
    /* inspect client->socketfd for errors */
    if (/* client->socketfd is in a bad state */) {
        client->error = MQTT_ERROR_SOCKET_ERROR;
        return client->error;
    }

    /* looks like the socket must be okay */
    return MQTT_OK;
}
```

To attach your inspector callback set `client->inspector_callback` to `my_socket_inspector` (this must be done _after_ your call to `mqtt_init` or `mqtt_init_reconnect`). Your socket inspector function will then be called on _every_ `mqtt_sync`.

Hope that helps. Let me know if you have any more questions.

Regards,

Liam

**Comment by LiamBindle** [comment]
Im going to close this issue. If you have more questions, feel free to reopen it, or create another issue.

Liam
