### ISSUE TITLE
error:failed to load the certificate

### ISSUE THREAD

**Issue by rosepinkr** [LiamBindle/MQTT-C#18]
I am having problems with running your openssl_publisher.
I get an error saying failed to load certificate.
My broker is on Amazon AWS EC2.
However if I try to publish with mosquitto command line with same parameters I am able to publish.

**Comment by rosepinkr** [comment]
Seems the certificate issue : x509 certificate verification failed, but when i use the same on mosquitto pub it works.

**Comment by LiamBindle** [comment]
Hi,

I'm actually not too familiar with TLS/SSL so I might not be the best person to help debug this, but I can try. I'm also moving right now, so I apologize if my responses are slow (also I don't have access to my computer right now so I can't try to reproduce).

In `templates/openssl_sockets.h` I have written a barebones function&mdash;called `open_nb_socket`&mdash;that opens a secure connection and returns the associated BIO socket (this function is called in the openssl_publisher example). To get MQTT-C working on an encrypted connection you must create this BIO socket (i.e. open and verify the connection) and that's it. 

I think that you will have to do some debugging in this function. If you are getting an error saying that the certificate failed to load then `SSL_CTX_load_verify_locations` on line 16 of [tempaltes/openssl_sockets.h](https://github.com/LiamBindle/MQTT-C/blob/master/examples/templates/openssl_sockets.h#L16) must be returning false. I'd start with figuring out why this is.

You could also check that there aren't any SSL errors immediately after loading OpenSSL (i.e. check the state of OpenSSL error at line 50 of [openssl_publisher.c](https://github.com/LiamBindle/MQTT-C/blob/master/examples/openssl_publisher.c#L50).

Here are some resources for error handling in OpenSSL:
- https://en.wikibooks.org/wiki/OpenSSL/Error_handling
- https://www.openssl.org/docs/man1.1.0/crypto/ERR_print_errors_fp.html
- https://stackoverflow.com/questions/37980798/openssl-error-handling
- https://www.ibm.com/developerworks/library/l-openssl/index.html

Let me know how it goes and if there is anything I can help you with.

Best regards,

Liam

**Comment by LiamBindle** [comment]
Because of inactivity, I'm going to assume this issue can be closed.

Please feel free to reopen if you continue to have trouble.
