### ISSUE TITLE
MQTT 5.0 support

### ISSUE THREAD

**Issue by markusschaber** [LiamBindle/MQTT-C#20]
First: Thanks for your great work!

I want to kindly ask about the plans / roadmap of supporting MQTT 5.0.

MQTT 5.0 standard is almost finished, it's very unlikely that there will be greater changes against the current draft.

Mosquitto announced commercial sponsoring for 5.0 protocol development: https://mosquitto.org/blog/2018/05/press-release/

There's public brokers available for testing: https://github.com/chkr1011/MQTTnet/issues/246#issuecomment-404783414

So I think now is a good time to clarify whether MQTT 5.0 support is planned, and what's the timeframe (and whether contributions are welcome).

Or just close this issue with won't fix, to document that 5.0 support is not planned...

[Edit: I've been mislead by some press articles which stated that MQTT 5.0 is [officially published](https://www.heise.de/developer/meldung/Internet-of-Things-MQTT-5-Standard-offiziell-freigegeben-3932569.html) - while it's almost finished, official release is more likely to happen[ in Q3 or Q4](https://github.com/eclipse/paho.mqtt.embedded-c/issues/102#issuecomment-405234654).]

**Comment by LiamBindle** [comment]
Hi Markus,

I'm glad you're pleased with it!

Personally I don't have plans to update support for V5.0, but **contributions are absolutely welcome**! I'd like to add support for the updated standard, but right now I just don't have the time. Recently I started on some new work, and for at least the next few months, I won't be able to dedicate much time to this project.

With that being said, I'm very receptive to contributions, and I'd be happy to help anyone that undertakes this. I took a quick glance at the new standard and I don't think it would be too big of an undertaking (anyone that intends to, please let me know if you need help getting started). When I designed the flow of MQTT-C, I tried to make it as simple/flexible as possible with the hope of making changes like these easy.

I'm going to mark this with as "help wanted" in the meantime.

Hope this answers your question, and let me know if I can help in any way.

Liam

**Comment by markusschaber** [comment]
Hi, Liam,

Yes, this fully answers my question, thanks! :-)

I'll keep you updated in case we'll jump on this train.

Markus

**Comment by LiamBindle** [comment]
I'm going to mark this "wontfix" because I'm not going to have the time to implement it in the foreseeable future.

If anyone would like to take this on, please let me know and I'd be happy to help get you started.

Liam
