### ISSUE TITLE
unaligned access exception

### ISSUE THREAD

**Issue by szemzoa** [LiamBindle/MQTT-C#27]
Hi,

First, thanks for your work!

I try to use the client on a cortex-m0+ SoC, and it works great with QOS0. 
With QOS1 it throws an unaligned exception, in function 

ssize_t mqtt_pack_pubxxx_request(uint8_t *buf, size_t bufsz,
                                enum MQTTControlPacketType control_type,
                                uint16_t packet_id)

when packed_id is casted at *(uint16_t*) buf = (uint16_t) MQTT_PAL_HTONS(packet_id);

It tries to write to address buf + 67 an uint16 packed_id variable, what is an unaligned exception on some arch.
So my proposal is to change ALL uint16_t casts to uint8_t buf to use memcpy, or use some kind of put_unaligned macros. 

Regards,
Andras

**Comment by LiamBindle** [comment]
Sorry that closing this issue took so long. Again, **thanks to @jepaan for the fix**.
