### ISSUE TITLE
Cmoka new repo

### ISSUE THREAD

**Issue by paolo-pr** [LiamBindle/MQTT-C#34]
Hello Liam,

this is just a little note to tell you that the CMOKA website linked by your page has broken/old versions, hard to install. According to this post:

https://github.com/clibs/cmocka/issues/13

...the right repo where to find the new versions, without installation issues should be this:

https://git.cryptomilk.org/projects/cmocka.git/

I installed without problems the last version taken from there, and had troubles with the versions pointed by cmoka.org website. So, consider to update your README.
In addition, I finally included your excellent library in my project, and made a MQTT full compliant A/V recording/streaming system:

https://github.com/paolo-pr/laav/blob/master/mqtt-avsystem/README.md

Any feedback is appreciated!

**Comment by LiamBindle** [comment]
Hi Paolo,

Thanks for letting me know! I'll look into this this weekend. 

Also, thanks for the feedback. It's always nice to hear where this project is being used. You're MQTT-AVSystem project looks really interesting! I'll comb through it this weekend.

Cheers,

Liam

**Comment by LiamBindle** [comment]
Hi Paolo,

I have decided to leave the link to cmocha's official website in the README&mdash;hopefully they will resolve this at their end in a timely manner. Until then, this issue will be a useful reference.

For anyone having trouble building cmocha from source, try downloading the cmocha source from:

> **https://git.cryptomilk.org/projects/cmocka.git/**

Thanks again @paolo-pr for bringing this up,

Liam
