### ISSUE TITLE
MQTT_ERROR_CONTROL_FORBIDDEN_TYPE error with QOS_1 

### ISSUE THREAD

**Issue by TonyTheLion** [LiamBindle/MQTT-C#38]
I am using your library on an embedded device and its mostly working quite well, but I've run into an issue with receiving messages that were sent from Azure IOTHUB while the device is not connected to iothub.

The device connects only every so often to iothub to check for messages from the server and send messages to the server.  It then disconnects the underlying socket and does a mqtt_reinit on the next connection to start again.

The issue I'm running into specifically is that when I set `1` in `mqtt_subscribe` in the `max_qos` argument to guarantee that I will get any messages from the server that were sent while I was offline, it gives me the `MQTT_ERROR_CONTROL_FORBIDDEN_TYPE `  specifically in the following conditions

1) I send more than 1 message to the device while it is offline, it comes online and then receives the first message.  After which it will (I assume) send an ack and whatever it receives next has a header with a control_type of 0x0 causing the `MQTT_ERROR_CONTROL_FORBIDDEN_TYPE `
error.  

After that error has occured I can no longer send anything to the server.  When it reconnects again later it will receive the **same** message it already received and error again on the same thing.  It doesn't even get to the second message.

Repeating this on every reconnect until the server stops sending the message.

2) The second scenario is when setting the `mqtt_publish` side to `MQTT_PUBLISH_QOS_1 as well as the `mqtt_subscribe` side.  Then I only ever get that `MQTT_ERROR_CONTROL_FORBIDDEN_TYPE` error and I cannot even receive one message.

I wondered if you had any insight as to why this might be happening?

**Comment by LiamBindle** [comment]
The error `MQTT_ERROR_CONTROL_FORBIDDEN_TYPE ` is set when the fixed header's control type is invalid/reserved value. According to the MQTT v3.1.1 spec, the control type values of 0 and 15 are reserved ([see here](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc385349209)).

The only place where `MQTT_ERROR_CONTROL_FORBIDDEN_TYPE ` is actually ever set is 
https://github.com/LiamBindle/MQTT-C/blob/201a2773308f1d7b629c2f9f58dd7178790e9c87/src/mqtt.c#L924-L926
so I suspect your issue must be coming from here. Also for your reference, `mqtt_fixed_header_rules::control_type_is_valid` is initialized here
https://github.com/LiamBindle/MQTT-C/blob/201a2773308f1d7b629c2f9f58dd7178790e9c87/src/mqtt.c#L855-L871
which is just the implementation of the section of the spec that I referenced above.

So, somehow `mqtt_pack_fixed_header` must be getting called with `fixed_header->control_type == 0`. That means somwhere in here
https://github.com/LiamBindle/MQTT-C/blob/201a2773308f1d7b629c2f9f58dd7178790e9c87/src/mqtt.c#L1237-L1259
the value must be getting set to 0.

I haven't seen this before, but I'm struggling to see how `fixed_header->control_type` is changing after L1237. I'll revisit this sometime in the next couple days.

**Comment by LiamBindle** [comment]
Have you made any progress with tracking down what is going on?

So the messages with `control_type` of 0 are coming from Azure IOTHUB? If so, I believe the error would be on their end. It could also be a problem with how MQTT-C is parsing the fixed headers it receives (I haven't heard of this before though).

If the messages with `control_type` 0 are being generated by MQTT-C then you might have to step through lines I posted above and see at what point the `control_type`  is being changed to 0.

Hope that helps, let me know how you're making out.

Liam

**Comment by TonyTheLion** [comment]
I've done some more testing, and it does look like we are receiving messages from Azure IOTHUB which have the wrong `control_type`.  

I sent two messages from the Azure website to my device while the device is not connected.  The messages had the following content:

`test`
`test 1`

I added some prints into the MQTT-C code, specifically where it unpacks the fixed header and the send/receive calls. Here is the output:

```
__mqtt_recv err: 1
mqtt_pal_recvall
fixed_header.control_type: 0x2
fixed_header.control_flags: 0x0
fixed_header.remaining_length: 0x2
mqtt_pal_recvall
fixed_header.control_type: 0x3
fixed_header.control_flags: 0x2
fixed_header.remaining_length: 0x77
[PRN] dispatch_mqtt.c:072 +publish_response_callback    :: publish_response_callback
[PRN] dispatch_mqtt.c:074 +publish_response_callback    :: test
mqtt_pal_recvall
fixed_header.control_type: 0x0
fixed_header.control_flags: 0x0
fixed_header.remaining_length: 0x79
header rule violation: -2147483646
__mqtt_recv err: -2147483646
[ERR] dispatch_mqtt.c:588 +mqtt_sync_callback   :: MQTT_ERROR_CONTROL_FORBIDDEN_TYPE
mqtt_pal_recvall
```

You can see we receive the first `test` correctly and then the second one it seems to receive the length of the packet (`0x79` - two bytes longer than the first which makes sense) but the `control_type` is `0`.

**Comment by LiamBindle** [comment]
Okay. Do you know if the packet sent by Azure IOTHUB has a `control_type` of 0, or if MQTT-C is parsing the packet incorrectly resulting in a `control_type` of 0? You could use Wireshark to inspect the ingress packets (format of the fixed_header is [here](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718020)). If you're having trouble interpreting the bytes of the packet, you could post a screenshot and I could give you a hand. 

This would let us figure out it's an MQTT-C problem or an Azure IOTHUB problem.

**Comment by TonyTheLion** [comment]
I can definitely do a tcpdump but the connection is encrypted so you can't see the headers of the MQTT packets.  Azure won't let me do unencrypted connections.  

I can do a print of the raw bytes that come in on my end tho, if that is any help?

**Comment by LiamBindle** [comment]
Yeah, the encrypted bytes are no use, but if you could print the raw bytes that come in on your end we could take a look at that. Essentially, if you could dump the buffer `buf` here https://github.com/LiamBindle/MQTT-C/blob/201a2773308f1d7b629c2f9f58dd7178790e9c87/src/mqtt.c#L1644
right before you get the `MQTT_ERROR_CONTROL_FORBIDDEN_TYPE` error.

**Comment by TonyTheLion** [comment]
Sent the following while device is offline
`test`
`test 1`

so capturing that data gives the following:

```
received bytes:
0x20 0x2 0x1 0x0 0x32 0x77 0x0 0x6f 0x64 0x65 0x76 0x69 0x63 0x65 0x73 0x2f 0x6a 0x61 0x72 0x65 0x64 0x5f 0x62 0x65 0x61 0x67 0x6c 0x65 0x5f 0x62 0x6c 0x61 0x63 0x6b 0x2f 0x6d 0x65 0x73 0x73 0x61 0x67 0x65 0x73 0x2f 0x64 0x65 0x76 0x69 0x63 0x65 0x62 0x6f 0x75 0x6e 0x64 0x2f 0x25 0x32 0x34 0x2e 0x74 0x6f 0x3d 0x25 0x32 0x46 0x64 0x65 0x76 0x69 0x63 0x65 0x73 0x25 0x32 0x46 0x6a 0x61 0x72 0x65 0x64 0x5f 0x62 0x65 0x61 0x67 0x6c 0x65 0x5f 0x62 0x6c 0x61 0x63 0x6b 0x25 0x32 0x46 0x6d 0x65 0x73 0x73 0x61 0x67 0x65 0x73 0x25 0x32 0x46 0x64 0x65 0x76 0x69 0x63 0x65 0x42 0x6f 0x75 0x6e 0x64 0x0 0x75 0x74 0x65 0x73 0x74 0x32 0x79 0x0 0x6f 0x64 0x65 0x76 0x69 0x63 0x65 0x73 0x2f 0x6a 0x61 0x72 0x65 0x64 0x5f 0x62 0x65 0x61 0x67 0x6c 0x65 0x5f 0x62 0x6c 0x61 0x63 0x6b 0x2f 0x6d 0x65 0x73 0x73 0x61 0x67 0x65 0x73 0x2f 0x64 0x65 0x76 0x69 0x63 0x65 0x62 0x6f 0x75 0x6e 0x64 0x2f 0x25 0x32 0x34 0x2e 0x74 0x6f 0x3d 0x25 0x32 0x46 0x64 0x65 0x76 0x69 0x63 0x65 0x73 0x25 0x32 0x46 0x6a 0x61 0x72 0x65 0x64 0x5f 0x62 0x65 0x61 0x67 0x6c 0x65 0x5f 0x62 0x6c 0x61 0x63 0x6b 0x25 0x32 0x46 0x6d 0x65 0x73 0x73 0x61 0x67 0x65 0x73 0x25 0x32 0x46 0x64 0x65 0x76 0x69 0x63 0x65 0x42 0x6f 0x75 0x6e 0x64 0x0 0x76 0x74 0x65 0x73 0x74 0x20 0x32
fixed_header.control_type: 0x2
fixed_header.control_flags: 0x0
fixed_header.remaining_length: 0x2
mqtt_pal_recvall
received bytes:
0x32 0x77 0x0 0x6f 0x64 0x65 0x76 0x69 0x63 0x65 0x73 0x2f 0x6a 0x61 0x72 0x65 0x64 0x5f 0x62 0x65 0x61 0x67 0x6c 0x65 0x5f 0x62 0x6c 0x61 0x63 0x6b 0x2f 0x6d 0x65 0x73 0x73 0x61 0x67 0x65 0x73 0x2f 0x64 0x65 0x76 0x69 0x63 0x65 0x62 0x6f 0x75 0x6e 0x64 0x2f 0x25 0x32 0x34 0x2e 0x74 0x6f 0x3d 0x25 0x32 0x46 0x64 0x65 0x76 0x69 0x63 0x65 0x73 0x25 0x32 0x46 0x6a 0x61 0x72 0x65 0x64 0x5f 0x62 0x65 0x61 0x67 0x6c 0x65 0x5f 0x62 0x6c 0x61 0x63 0x6b 0x25 0x32 0x46 0x6d 0x65 0x73 0x73 0x61 0x67 0x65 0x73 0x25 0x32 0x46 0x64 0x65 0x76 0x69 0x63 0x65 0x42 0x6f 0x75 0x6e 0x64 0x0 0x75 0x74 0x65 0x73 0x74 0x32 0x79 0x0 0x6f 0x64 0x65 0x76 0x69 0x63 0x65 0x73 0x2f 0x6a 0x61 0x72 0x65 0x64 0x5f 0x62 0x65 0x61 0x67 0x6c 0x65 0x5f 0x62 0x6c 0x61 0x63 0x6b 0x2f 0x6d 0x65 0x73 0x73 0x61 0x67 0x65 0x73 0x2f 0x64 0x65 0x76 0x69 0x63 0x65 0x62 0x6f 0x75 0x6e 0x64 0x2f 0x25 0x32 0x34 0x2e 0x74 0x6f 0x3d 0x25 0x32 0x46 0x64 0x65 0x76 0x69 0x63 0x65 0x73 0x25 0x32 0x46 0x6a 0x61 0x72 0x65 0x64 0x5f 0x62 0x65 0x61 0x67 0x6c 0x65 0x5f 0x62 0x6c 0x61 0x63 0x6b 0x25 0x32 0x46 0x6d 0x65 0x73 0x73 0x61 0x67 0x65 0x73 0x25 0x32 0x46 0x64 0x65 0x76 0x69 0x63 0x65 0x42 0x6f 0x75 0x6e 0x64 0x0 0x76 0x74 0x65 0x73 0x74 0x20 0x32
fixed_header.control_type: 0x3
fixed_header.control_flags: 0x2
fixed_header.remaining_length: 0x77
[PRN] dispatch_mqtt.c:072 +publish_response_callback    :: publish_response_callback
[PRN] dispatch_mqtt.c:074 +publish_response_callback    :: test
mqtt_pal_recvall
received bytes:
0x0 0x79 0x0 0x6f 0x64 0x65 0x76 0x69 0x63 0x65 0x73 0x2f 0x6a 0x61 0x72 0x65 0x64 0x5f 0x62 0x65 0x61 0x67 0x6c 0x65 0x5f 0x62 0x6c 0x61 0x63 0x6b 0x2f 0x6d 0x65 0x73 0x73 0x61 0x67 0x65 0x73 0x2f 0x64 0x65 0x76 0x69 0x63 0x65 0x62 0x6f 0x75 0x6e 0x64 0x2f 0x25 0x32 0x34 0x2e 0x74 0x6f 0x3d 0x25 0x32 0x46 0x64 0x65 0x76 0x69 0x63 0x65 0x73 0x25 0x32 0x46 0x6a 0x61 0x72 0x65 0x64 0x5f 0x62 0x65 0x61 0x67 0x6c 0x65 0x5f 0x62 0x6c 0x61 0x63 0x6b 0x25 0x32 0x46 0x6d 0x65 0x73 0x73 0x61 0x67 0x65 0x73 0x25 0x32 0x46 0x64 0x65 0x76 0x69 0x63 0x65 0x42 0x6f 0x75 0x6e 0x64 0x0 0x76 0x74 0x65 0x73 0x74 0x20 0x32
fixed_header.control_type: 0x0
fixed_header.control_flags: 0x0
fixed_header.remaining_length: 0x79
header rule violation: -2147483646
__mqtt_recv err: -2147483646
[ERR] dispatch_mqtt.c:588 +mqtt_sync_callback   :: MQTT_ERROR_CONTROL_FORBIDDEN_TYPE
```

It does seem like they send us a null byte from what I can tell.

**Comment by LiamBindle** [comment]
Here's my interpretation of the packets:

Packet 1 (this is actually more than one packet):
```
0x20 0x2 0x1 0x0 0x32 0x77 0x0 0x6f 0x64 0x65 0x76 0x69 0x63 0x65 0x73 0x2f 0x6a 0x61 0x72 0x65 0x64 0x5f 0x62 0x65 0x61 0x67 0x6c 0x65 0x5f 0x62 0x6c 0x61 0x63 0x6b 0x2f 0x6d 0x65 0x73 0x73 0x61 0x67 0x65 0x73 0x2f 0x64 0x65 0x76 0x69 0x63 0x65 0x62 0x6f 0x75 0x6e 0x64 0x2f 0x25 0x32 0x34 0x2e 0x74 0x6f 0x3d 0x25 0x32 0x46 0x64 0x65 0x76 0x69 0x63 0x65 0x73 0x25 0x32 0x46 0x6a 0x61 0x72 0x65 0x64 0x5f 0x62 0x65 0x61 0x67 0x6c 0x65 0x5f 0x62 0x6c 0x61 0x63 0x6b 0x25 0x32 0x46 0x6d 0x65 0x73 0x73 0x61 0x67 0x65 0x73 0x25 0x32 0x46 0x64 0x65 0x76 0x69 0x63 0x65 0x42 0x6f 0x75 0x6e 0x64 0x0 0x75 0x74 0x65 0x73 0x74 0x32 0x79 0x0 0x6f 0x64 0x65 0x76 0x69 0x63 0x65 0x73 0x2f 0x6a 0x61 0x72 0x65 0x64 0x5f 0x62 0x65 0x61 0x67 0x6c 0x65 0x5f 0x62 0x6c 0x61 0x63 0x6b 0x2f 0x6d 0x65 0x73 0x73 0x61 0x67 0x65 0x73 0x2f 0x64 0x65 0x76 0x69 0x63 0x65 0x62 0x6f 0x75 0x6e 0x64 0x2f 0x25 0x32 0x34 0x2e 0x74 0x6f 0x3d 0x25 0x32 0x46 0x64 0x65 0x76 0x69 0x63 0x65 0x73 0x25 0x32 0x46 0x6a 0x61 0x72 0x65 0x64 0x5f 0x62 0x65 0x61 0x67 0x6c 0x65 0x5f 0x62 0x6c 0x61 0x63 0x6b 0x25 0x32 0x46 0x6d 0x65 0x73 0x73 0x61 0x67 0x65 0x73 0x25 0x32 0x46 0x64 0x65 0x76 0x69 0x63 0x65 0x42 0x6f 0x75 0x6e 0x64 0x0 0x76 0x74 0x65 0x73 0x74 0x20 0x32
```
- `0x20 0x2 0x1 0x0`: this is the CONNACK
- `0x32 0x77`: this is the fixed header of the received PUBLISH, and it says there are 119 bytes after the 0x77 byte in the packet.
- `0x0 0x6f`: this says your topic name is 111 characters long
- `0x64 0x65 0x76 0x69 0x63 0x65 0x73 0x2f 0x6a 0x61 0x72 0x65 0x64 0x5f 0x62 0x65 0x61 0x67 0x6c 0x65 0x5f 0x62 0x6c 0x61 0x63 0x6b 0x2f 0x6d 0x65 0x73 0x73 0x61 0x67 0x65 0x73 0x2f 0x64 0x65 0x76 0x69 0x63 0x65 0x62 0x6f 0x75 0x6e 0x64 0x2f 0x25 0x32 0x34 0x2e 0x74 0x6f 0x3d 0x25 0x32 0x46 0x64 0x65 0x76 0x69 0x63 0x65 0x73 0x25 0x32 0x46 0x6a 0x61 0x72 0x65 0x64 0x5f 0x62 0x65 0x61 0x67 0x6c 0x65 0x5f 0x62 0x6c 0x61 0x63 0x6b 0x25 0x32 0x46 0x6d 0x65 0x73 0x73 0x61 0x67 0x65 0x73 0x25 0x32 0x46 0x64 0x65 0x76 0x69 0x63 0x65 0x42 0x6f 0x75 0x6e 0x64`: this is your topic name
- `0x0 0x75`: this is your packet ID
- `0x74 0x65 0x73 0x74`: this is your application message (i.e. "test")
- So this packet appear okay.

But now I see something weird. The byte immediately following the last "t" changes from 0x32 (the correct first byte of the next PUBLISH packet) to 0x00. See here:
![image](https://user-images.githubusercontent.com/12772306/57734186-b4527780-7677-11e9-86a1-00a3247be415.png)
So somehow the buffer is changing. I don't really know how this could be happening though because `buf` is `const` in `mqtt_unpack_response`.

Oh, maybe...
When your callback gets the packet, are you writing a null character at the end (to make it a c-string)? `response->application_message` points to the position in the buffer that contains the application message (see [mqtt.c:1316](https://github.com/LiamBindle/MQTT-C/blob/master/src/mqtt.c#L1316)), so if you were to modify this it would mess up the buffer.

**Comment by TonyTheLion** [comment]
> When your callback gets the response struct, are you writing a null character at the end (to make it a c-string)? response->application_message points to the position in the buffer that contains the application message (see mqtt.c:1316), so if you were to modify this it would mess up the ingress buffer.

Yes that was it.  I was printing the `publish->application_message` in the callback and because it would print junk after the text, I wrote a `\0` after it.  

Removing that line fixed the issue with receive.  

Thank you so much for your help in debugging this.

**Comment by LiamBindle** [comment]
Glad to help. 

Let me know if you run into any more problems.
