### ISSUE TITLE
I Wants to implement MQTT applications as full duplex application

### ISSUE THREAD

**Issue by akbarsaleemt** [LiamBindle/MQTT-C#43]
In this simplex communication implemented but I need to implement duplex communication.
I tried that also but getting same results on both sides, I modified the code as below.
/*****************************PUBLISHER*******************************************************/
	printf("Press CTRL-D (or any other key) to exit.\n\n");
	start1:	while(fgetc(stdin) == '\n') {
	 
		time_t timer;
		time(&timer);
		struct tm* tm_info = localtime(&timer);
		char timebuf[26];
		bzero(timebuf,26);
		strftime(timebuf, 26, "%Y-%m-%d %H:%M:%S", tm_info);
		char application_message[256];
		bzero(application_message,256);
		topic ="datetime";
		printf("Press ENTER to publish the current time.\n");
		snprintf(application_message, sizeof(application_message), "The time is %s", tm_info);
		mqtt_publish(&client, topic, application_message, strlen(application_message) + 1, MQTT_PUBLISH_QOS_0);
		if (client.error != MQTT_OK) {
			fprintf(stderr, "error: %s\n", mqtt_error_str(client.error));
			exit_example(EXIT_FAILURE, sockfd, &client_daemon);
		}
		topic="temperature";
		/* subscribe */
		mqtt_subscribe(&client, topic, 0);
		goto start1;
	}   
/*********************************************************************************************************************/
/******************************************subscriber code*************************************************/
start:	while(fgetc(stdin) == '\n'){	
	
		topic="datetime";
		/* subscribe */
		mqtt_subscribe(&client, topic, 0);
		/* start publishing the time */
		char application_message[256];
		bzero(application_message,256);
		topic ="temperature";
		char temperature[]="45";
		snprintf(application_message, sizeof(application_message), "The temperature is %s", temperature); 
		printf("Press ENTER to publish the current Temperature\n");   
		getchar(); 
		mqtt_publish(&client, topic, application_message, strlen(application_message) + 1, MQTT_PUBLISH_QOS_0);
		if (client.error != MQTT_OK) {
			fprintf(stderr, "error: %s\n", mqtt_error_str(client.error));
			exit_example(EXIT_FAILURE, sockfd, &client_daemon);
		}
		
		printf("Press CTRL-D to exit.\n\n");
		goto start;
	}
/*********************************************************************************************************************/

Thankyou,
Akbar

**Comment by LiamBindle** [comment]
Hi Akbar,

I'm not entirely sure I understand what you've done (i.e. what modifications you've made, how you're running your clients, etc.) and what you're seeing (i.e. what output the clients are giving you). 

Based on what you said, I'm guessing you essentially combined `examples/simple_publisher.c` and `examples/simple_subscriber.c` into a single executable. Then, I'm guessing you're running that executable twice. Is this correct?

If so, you can see that both clients are publishing and subscribing to the same topic. So it would make sense that you're getting the same results on both sides.

Hope that helps! If not, please provide more information to clarify what you've done and what you're seeing.

Liam

**Comment by LiamBindle** [comment]
I'm going to close this issue. Feel free to reopen it if you want.
