### ISSUE TITLE
Support other build systems

### ISSUE THREAD

**Issue by learn-more** [LiamBindle/MQTT-C#48]
Hello,

Currently there is only a makefile to build with gcc,
would a PR to add a visual studio solution be accepted?

Or would a system like CMake be preferred in thatcase?

Regards,

Mark

**Comment by LiamBindle** [comment]
Hi @learn-more,

Absolutely! My preference would be CMake because that will cover more cases.

Liam

**Comment by learn-more** [comment]
I tried it on windows using wsl already (just to get a feel for it), that seemed to work except for the bio example. (Did not investigate, but there was an error at runtime).

As for winsock: This is on my todo list, but that is several miles long already so no idea about a timeframe.

**Comment by LiamBindle** [comment]
Sounds good. Let me know if there's anything I can help with.

**Comment by LiamBindle** [comment]
Closed in #62
