### ISSUE TITLE
Error when creating a function

### ISSUE THREAD

**Issue by JohnSmith2591** [LiamBindle/MQTT-C#54]
Hello,

First of all I appologize if I did something wrong nor a noob mistake. I'm not used to code.
Your example runs flawlessly and it is straight forward. I tried to create functions to perform opening socket task, publish and so on to get a much clearer main().
Then I get a segmentation error I can't understand.

Here is my modified code
`#include <unistd.h>
#include <stdlib.h>
#include <stdio.h>

#include <mqtt.h>
#include "examples/templates/posix_sockets.h"

int sockfd;
pthread_t client_daemon;

/**
 * @brief The function that would be called whenever a PUBLISH is received.
 * 
 * @note This function is not used in this example. 
 */
void publish_callback(void** unused, struct mqtt_response_publish *published);

/**
 * @brief The client's refresher. This function triggers back-end routines to 
 *        handle ingress/egress traffic to the broker.
 * 
 * @note All this function needs to do is call \ref __mqtt_recv and 
 *       \ref __mqtt_send every so often. I've picked 100 ms meaning that 
 *       client ingress/egress traffic will be handled every 100 ms.
 */
void* client_refresher(void* client);

/**
 * @brief Safelty closes the \p sockfd and cancels the \p client_daemon before \c exit. 
 */
void exit_example(int status, int sockfd, pthread_t *client_daemon);

/**
 * A simple program to that publishes the current temperature whenever ENTER is pressed. 
 */
 
void open_mqtt_socket(const char *, const char *, const char *, struct mqtt_client *);
 

int main(int argc, const char *argv[])
{
    const char* addr;
    const char* port;
    const char* topic;

    /* get address (argv[1] if present) */
    if (argc > 1) {
        addr = argv[1];
    } else {
        addr = "test.mosquitto.org";
    }

    /* get port number (argv[2] if present) */
    if (argc > 2) {
        port = argv[2];
    } else {
        port = "1883";
    }

    /* get the topic name to publish */
    if (argc > 3) {
        topic = argv[3];
    } else {
        topic = "mytopic";
    }

    ///////////////////////////////////
    
    struct mqtt_client client;
    open_mqtt_socket(addr, port, topic, &client);

    /* start a thread to refresh the client (handle egress and ingree client traffic) */
    /*pthread_t client_daemon;
    if(pthread_create(&client_daemon, NULL, client_refresher, &client)) {
        fprintf(stderr, "Failed to start client daemon.\n");
        exit_example(EXIT_FAILURE, sockfd, NULL);
    }
*/   
    /* start publishing the time */
    printf("%s is ready to begin publishing the temperature.\n", argv[0]);
    printf("Press ENTER to start .\n");
    printf("Press CTRL-D (or any other key) to exit.\n\n");
    float temp=20.0;
    char application_message[6];
    while(1) {
		
		/* print a message */
		snprintf(application_message, sizeof(application_message), "%f", temp);
		printf("%s published : \"%s\"\r\n", argv[0], application_message);
		
		/* publish the temperature */
        printf("Going to mqtt_publish\r\n");
        printf("longueur payload : %i\r\n", strlen(application_message));
        mqtt_publish(&client, topic, application_message, strlen(application_message) + 1, MQTT_PUBLISH_QOS_0);
        //mqtt_publish(&client, "garage", "toto", 4, MQTT_PUBLISH_QOS_0);

        /* check for errors */
        if (client.error != MQTT_OK) {
            fprintf(stderr, "error: %s\n", mqtt_error_str(client.error));
            exit_example(EXIT_FAILURE, sockfd, &client_daemon);
        }
        sleep(1);
        temp++;
	}
	
	/* disconnect */
    printf("\n%s disconnecting from %s\n", argv[0], addr);
    sleep(1);

    /* exit */ 
    exit_example(EXIT_SUCCESS, sockfd, &client_daemon);
		
}

void exit_example(int status, int sockfd, pthread_t *client_daemon)
{
    if (sockfd != -1) close(sockfd);
    if (client_daemon != NULL) pthread_cancel(*client_daemon);
    exit(status);
}

void publish_callback(void** unused, struct mqtt_response_publish *published) 
{
    /* not used in this example */
}

void* client_refresher(void* client)
{
    while(1) 
    {
        mqtt_sync((struct mqtt_client*) client);
        usleep(100000U);
    }
    return NULL;
}

void open_mqtt_socket(const char *addr, const char *port, const char *topic, struct mqtt_client *client){
    
    /* open the non-blocking TCP socket (connecting to the broker) */
    int sockfd = open_nb_socket(addr, port);

    if (sockfd == -1) {
        perror("Failed to open socket: ");
        exit_example(EXIT_FAILURE, sockfd, NULL);
    }
    
    /* setup a client */
    //struct mqtt_client client;
    uint8_t sendbuf[2048]; /* sendbuf should be large enough to hold multiple whole mqtt messages */
    uint8_t recvbuf[1024]; /* recvbuf should be large enough any whole mqtt message expected to be received */
    mqtt_init(/*&*/client, sockfd, sendbuf, sizeof(sendbuf), recvbuf, sizeof(recvbuf), publish_callback);
    mqtt_connect(/*&*/client, "publishing_client", NULL, NULL, 0, NULL, NULL, 0, 400);

    /* check that we don't have any errors */
    if (client->error != MQTT_OK) {
        fprintf(stderr, "error: %s\n", mqtt_error_str(client->error));
        exit_example(EXIT_FAILURE, sockfd, NULL);
    }

    //pthread_t client_daemon;
    if(pthread_create(&client_daemon, NULL, client_refresher, /*&*/client)) {
        fprintf(stderr, "Failed to start client daemon.\n");
        exit_example(EXIT_FAILURE, sockfd, NULL);
    }
}`

So I basically moved all the mqtt_init and mqtt_connect stuff in open_mqtt_socket() function, created global variables for socket file descriptor and client_daemon pthread.
Then the failure occurs in mqtt_publish() when the macro MQTT_CLIENT_TRY_PACK calls mqtt_mq_register.

The line which makes the program hang is:
`mq->queue_tail->size = nbytes;`

What I don't understand is that  MQTT_CLIENT_TRY_PACK is called one time before being called by mqtt_publish(). And the first time it is called, no segmentation fault is raised.

I hope I was clear enough to make you able to reproduce the problem

Thank you for your help
With my best regards

**Comment by JohnSmith2591** [comment]
Sorry, it seems the 'Insert code' button did not appreciate my code copy/paste

**Comment by LiamBindle** [comment]
Hi, 

Thanks for the question. The thing that immediately jumps out to me is that you're allocating `sendbuf` and `recvbuf`on the stack&mdash;so `sendbuf` and `recvbuf` become invalid as soon as `open_mqtt_socket()` returns. You could fix this by allocating them with `malloc` and then explicitly passing their size to `mqtt_init()`.

Regards,

Liam

**Comment by JohnSmith2591** [comment]
Hello Liam

Thank you very much for your quick answer, and sorry for giving a so late feedback.
I have to thank you very much for your help. Following your advice make the magic happen.
Thanks a lot for your help and great work !

Best regards
Florent
