### ISSUE TITLE
Prevent Client from receiving its own messages

### ISSUE THREAD

**Issue by theanhhoang** [LiamBindle/MQTT-C#55]
Hi Liam,
Basically I am joining the simple_subscriber.c and simple_publisher.c into one script, then that can send and receive message at the same time. Now I am wondering that is any way that Client can prevent to receive its own published messages?
I know that we can do it by choosing different topic names, but I still want to find a better solution.

Thanks!

**Comment by MikhailNatalenko** [comment]
You suggest a wrong and unexpected MQTT client behaviour. I'm pretty sure that the client SHOULD get its own messages.

**Comment by LiamBindle** [comment]
I believe @MikhailNatalenko is right. If you subscribe and publish to the same topic, I think you'll receive your publishes. I haven't seen anything in the standard about this, but feel free to correct me if I'm wrong.

Liam
