### ISSUE TITLE
A mqtt_pal.c file for Windows?

### ISSUE THREAD

**Issue by brianreinhold** [LiamBindle/MQTT-C#56]
This looked so nice and simple until it turned out that I have to create the mqtt_pal.c file for my platform. It would be great if someone has already made such a file for Windows. It looks like it demands a significant amount of knowledge about sockets in Windows and I do not.

**Comment by LiamBindle** [comment]
Hi @brianreinhold,

@learn-more Added a Windows PAL in #53. I haven't had a chance to make a couple minor modifications to the CMakeLists, but you could get a Windows PAL from his PR.

Liam

**Comment by LiamBindle** [comment]
Added in #63
