### ISSUE TITLE
mqtt_subscribe and mqtt_publish is not ok when establishing encrypted channel based on TLS1.2

### ISSUE THREAD

**Issue by sawyerliu** [LiamBindle/MQTT-C#57]
Hello,
  the MQTT C code is run on MCU connects to mosquitto broker. using TLS1.2 to pass handshake, then mqtt_connect to broker and send pingres, all are ok. But when sending mqtt_publish and mqtt_subscribe, the broker will has an error. see attached file.
![Untitled](https://user-images.githubusercontent.com/49260033/68921641-592f4800-07b4-11ea-85c3-35255840bb1d.png)
![Untitled2](https://user-images.githubusercontent.com/49260033/68921722-9a275c80-07b4-11ea-89c2-4ccbd831d65a.png)

**Comment by LiamBindle** [comment]
Hi @sawyerliu, sorry for the delayed response. Are you still having problems? If so, could you provide some more information on your issue? Have you been able to diagnose what's causing the socket error? What MQTT-C error code do you get([see here](https://liambindle.ca/MQTT-C/group__api.html#gad0c901a8d30691ed0ca17915b691b7e7))?

**Comment by sawyerliu** [comment]
Hi Liam,
       The issue is resolved, maybe it is caused by router. The MQTT-C is very good for embedded device. Thanks.

Best Regards
Sawyer Liu(刘维峰)

**Comment by LiamBindle** [comment]
@sawyerliu 

Great! Glad things are working well for you.
