### ISSUE TITLE
BIO_do_connect will cause the application to exit if called after it has returned 0

### ISSUE THREAD

**Issue by sbovbjerg** [LiamBindle/MQTT-C#59]
In openssl_sockets.h BIO_do_connect is called repeatedly for 10 seconds or until it succeeds or fails. If the connection fails (i.e. there is no broker running), it will return 0. Calling it again after this will cause the process to exit from within the C runtime (in glibc on Linux, that is).

A possible solution is to exit the while loop if the BIO_do_connect returns 0, since is seem like the BIO will need to be re-initialized before it can be reused (or something). For the same reason, the extra call to BIO_do_connect after the while loop should not be made at it will also cause an exit. 

Note that this does not seem to affect unencrypted BIO sockets (as in bio_sockets.h) the same way.

Suggested change that seems to fix the issue:

```
    int conres = 0;
    
    while ((int)time(NULL) - start_time < 10) {
        conres = BIO_do_connect(*bio);
        if (conres >= 0) {
            break;
        }
    }
    
    if (conres <= 0) {
        BIO_free_all(*bio);
        SSL_CTX_free(*ssl_ctx);
        *bio = NULL;
        *ssl_ctx=NULL;
        return;
    }
```

... to replace line 29->39 in https://github.com/LiamBindle/MQTT-C/blob/master/examples/templates/openssl_sockets.h

That way, the error can be handled upon return instead and reconnect attempts can be made.

**Comment by LiamBindle** [comment]
Hi @sbovbjerg, thanks for opening this issue. I believe this should be fixed in 560f05a. Please let me know if there are any more issues.
