### ISSUE TITLE
Automatic recovery from MQTT_ERROR_SEND_BUFFER_IS_FULL

### ISSUE THREAD

**Issue by jedidiahuang** [LiamBindle/MQTT-C#7]
Hi

Thank you for MQTT-C contribution, it looks great and  I am  trying to use it in my linux embedded project.
I have experienced a problem of your Simple_Publisher.c:
When it is running and I press <Enter> key to publish current time,
If I press key too quick,  **mqtt_publish()** API return error: MQTT_ERROR_SEND_BUFFER_IS_FULL and no way to recover. 

If I add **mqtt_sync(**) after **mqtt_publish(),** it  work very well. Since you use large buffer and a thread to do 
 mqtt_sync() , I'd like to know how to recover when MQTT_ERROR_SEND_BUFFER_IS_FULL error appears.

Thanks a lot

**Comment by LiamBindle** [comment]
Hi Jedidiahuang,

You have a good point, once `MQTT_ERROR_SEND_BUFFER_IS_FULL` is set it will never be cleared (but it should). Just to clarify, are you running [simple_publisher.c](https://github.com/LiamBindle/MQTT-C/blob/master/examples/simple_publisher.c) which runs on two threads or have you adapted it to run in a single thread?

**Comment by jedidiahuang** [comment]
Dear Liam

 

Thank you for quick responding.

 

1.      I just type ‘make’ and run bin/simple_publisher.  You may practice by pressing <Enter> without releasing key and it’ll show error then stop. As your program wrote, there is a thread for mqtt_sync() and main thread to publish after pressing <enter>

2.      What I’ve concerned more is 

*  MQTT-C client publishing a topic to broker and subscribing it by another MQTT client tool, the result is shown below: 

*  You can see that simple_subscriber received the payload,published->application_message, missing first 2 byts.



*  Simple_publisher:



As you see, MQTT.fx received payload of ‘datetime’ has extra byte in binary code

at the beginning. I guess it’s a variable string with leading 2 bytes contain length of this string.



 

3.      It seems a bug? I’m tracing mqtt.c and try to fix subscribed payload just the same as published payload.

 

Thanks a lot and with my Best Regards,

 

Jedidiahuang

**Comment by LiamBindle** [comment]
I believe I've located the bug causing the first two bytes of the application message to be garbage for QoS 0 but I'd prefer to keep that discussion to the issue #8 thread (it will be fixed asap).

Regarding this issue (#7) I worked on it for a while last night and I believe I have a fix. I will update you in the next couple days (but automatic recover from `MQTT_ERROR_SEND_BUFFER_IS_FULL` should be relatively easy to implement).

Just as a note (for you or anyone else reading this thread) in general the safest way to handle error in MQTT-C (in my opinion) is to: (1) terminate the connection with the broker, (2) do any corrections if the error occured client-side (e.g. increase size of `sendbuf`), and (3) reestablish the connection to the broker.

Section 4.8 of the standard (line 1474-1484 of [mqtt-v3.1.1.pdf](https://github.com/LiamBindle/MQTT-C/files/1988611/mqtt-v3.1.1-os.pdf)) says that transient error should cause the client to disconnect. Currently, MQTT-C does not do this DISCONNECT upon going into an error state but this should be implemented. 

I will update you in the next couple of days.

Best regards,

Liam

**Comment by jedidiahuang** [comment]
Dear Liam,

I'm going to adopt your **MQTT-C** in my IoT embedded application for machine Data acquisition. 
This is the best embedded **MQTT Client API** I've ever learned. 

I'd suggest you  to  add one more argument,say, Reconnect, in mqtt_connect() API , to make MQTT  TCP Socket connection  be auto reconnected once connection is broken, instead of exit program and losing data.

My reason is that most IoT application is always keep running  silently in a small box controller. Once connection is broken, we have better to make MQTT connection be auto-reconnected instead of exit application.  

For example, an IoT DAQ project, application will send event or production information periodically.
Such as keep counting of yield quantity of machine's production and monitor Alarm trigger. 
In such application, if connection is broken and application must shutdown and re-spawned then all critical yield data will be lost.  

Another feature is let MQTT-C has Open SSL/TSL encryption capability, since most of MQTTＣlient API would support this issue.

If this improvements are achieved, this MQTT API will be highly appreciated.

However, thanks for your great contributions. 

Best Regards,
Victor

**Comment by LiamBindle** [comment]
That's great! Thank you, I'm glad you like it. I like both of your suggestions&mdash;I think SSL/TLS support would be a good addition, and the automatic reconnection sounds good too but I might need some clarification on what you mean. 

I'm going to suggest we move those discussions to their own issues, however.

Regards,

Liam

**Comment by LiamBindle** [comment]
I'm going to close this issue because I think it fits into the [Automatic reconnect](#11) enhancement. If anyone feels differently, please feel free to re-open this issue.
