### ISSUE TITLE
First two bytes incorrect for PUBLISH's with QoS 0

### ISSUE THREAD

**Issue by jedidiahuang** [LiamBindle/MQTT-C#8]
Dear Sir, 

I run MQTT-C simple_publisher to publish a topic '**DAQ**' with payload(application message) '**TEST123456789**'  and  run MQTT-fx (free tool) to Subscribe 'DAQ' to receive this message.
MQTT-fx show the received message with extra 2 binary code in the beginning.  '**?ST123456789**'
(? indicates a corrupted font)

Then I publish a topic '**datetime**' from MQTT-fx with a message '**2018/05/08 12:23:35**'
While MQTT-C simple_subscriber subscribed topic '**datetime**'. 
in this call back:
void publish_callback(void** unused, struct mqtt_response_publish *published)
{
    ...
    topic_name[published->topic_name_size] = '\0';
    printf("Received publish('%s'): %s\n", topic_name, (const char*) **published->application_message**);
...
}
the content of  **published->application_message**  is '**18/05/08 12:23:35**' , missing first 2 bytes
Is it a bug? How to fix it?

Thanks a lot.
![default](https://user-images.githubusercontent.com/2271416/39805974-1038fb6e-53ab-11e8-8727-956904c5c71d.png)
![default](https://user-images.githubusercontent.com/2271416/39805991-2128baae-53ab-11e8-8eac-7563f7e33133.png)
![default](https://user-images.githubusercontent.com/2271416/39806015-3e2a3fb0-53ab-11e8-8fe8-97b26daa977d.png)

**Comment by LiamBindle** [comment]
Hi Jedidiahuang,

Thanks for the issue submission, this is a bug and I've managed to locate it. First I'll highlight how I reproduced your error, then I'll explain the bug.

## Reproducing the bug

You are correct, it looks like something is wrong with the first two bytes of the application message. I was able to reproduce what you see using a local Mosquitto broker. This is what I see.

---

Broker: 
```bash
$ mosquitto -v -p 1884                             
1525878911: mosquitto version 1.4.8 (build date Thu, 01 Mar 2018 09:34:49 -0500) starting
1525878911: Using default config.
1525878911: Opening ipv4 listen socket on port 1884.
1525878911: Opening ipv6 listen socket on port 1884.
1525878935: New connection from 127.0.0.1 on port 1884.
1525878935: New client connected from 127.0.0.1 as publishing_client (c0, k400).
1525878935: Sending CONNACK to publishing_client (0, 0)
1525878948: New connection from 127.0.0.1 on port 1884.
1525878948: New client connected from 127.0.0.1 as subscribing_client (c0, k400).
1525878948: Sending CONNACK to subscribing_client (0, 0)
1525878948: Received SUBSCRIBE from subscribing_client
1525878948: 	datetime (QoS 0)
1525878948: subscribing_client 0 datetime
1525878948: Sending SUBACK to subscribing_client
1525878959: New connection from 127.0.0.1 on port 1884.
1525878959: New client connected from 127.0.0.1 as mosqsub/5264-workstatio (c1, k60).
1525878959: Sending CONNACK to mosqsub/5264-workstatio (0, 0)
1525878959: Received SUBSCRIBE from mosqsub/5264-workstatio
1525878959: 	datetime (QoS 0)
1525878959: mosqsub/5264-workstatio 0 datetime
1525878959: Sending SUBACK to mosqsub/5264-workstatio
1525878967: Received PUBLISH from publishing_client (d0, q0, r0, m0, 'datetime', ... (34 bytes))
1525878967: Sending PUBLISH to subscribing_client (d0, q0, r0, m0, 'datetime', ... (34 bytes))
1525878967: Sending PUBLISH to mosqsub/5264-workstatio (d0, q0, r0, m0, 'datetime', ... (34 bytes))
1525878969: Received PUBLISH from publishing_client (d0, q0, r0, m0, 'datetime', ... (34 bytes))
1525878969: Sending PUBLISH to subscribing_client (d0, q0, r0, m0, 'datetime', ... (34 bytes))
1525878969: Sending PUBLISH to mosqsub/5264-workstatio (d0, q0, r0, m0, 'datetime', ... (34 bytes))
^C1525878978: mosquitto version 1.4.8 terminating
```

---

Publisher ([simple_publisher.c](https://github.com/LiamBindle/MQTT-C/blob/master/examples/simple_publisher.c)):
```bash
$ ./bin/simple_publisher 0.0.0.0 1884  
./bin/simple_publisher is ready to begin publishing the time.
Press ENTER to publish the current time.
Press CTRL-D (or any other key) to exit.


./bin/simple_publisher published : "The time is 2018-05-09 09:16:07"
./bin/simple_publisher published : "The time is 2018-05-09 09:16:09"
./bin/simple_publisher disconnecting from 0.0.0.0
```
---
Mosquitto Subscriber:
```bash
$ mosquitto_sub -h localhost -p 1884 -v -t datetime
datetime �QThe time is 2018-05-09 09:16:07
datetime �(The time is 2018-05-09 09:16:09
```
---

I found that I could reproduce these bad characters with [simple_subscriber.c](https://github.com/LiamBindle/MQTT-C/blob/master/examples/simple_subscriber.c) by changing this line

https://github.com/LiamBindle/MQTT-C/blob/5e18fed8c6e8f1015e809819da9a88dc77de52f0/examples/simple_subscriber.c#L123

to

```c
printf("Received publish('%s'): %s\n", topic_name, (const char*) published->application_message - 2); 
```

The resulting output was this:

```bash
$ ./bin/simple_subscriber 0.0.0.0 1884 
./bin/simple_subscriber listening for 'datetime' messages.
Press CTRL-D to exit.

Received publish('datetime'): �QThe time is 2018-05-09 09:16:07
Received publish('datetime'): �(The time is 2018-05-09 09:16:09
```

---

## Diagnosing the bug
One thing to notice is that the first character is always "�Q" and the second character is "�(". The last two characters of the variable header (two bytes preceding the payload) are the packet ID. MQTT-C uses an LFSR to generate packet ID's which would explain why the same sequence of bad characters shows up.

It turns our packet ID's are only supposed to be included in the variable header for PUBLISH's with QOS > 0 (see [mqtt-v3.1.1.pdf]() line 799-801). In `mqtt_pack_publish_request` packet ID's are being included in the variable header _for all_ QoS levels (see snippet below). This means that **this bug should only be present for PUBLISH's with QoS 0**.

https://github.com/LiamBindle/MQTT-C/blob/5e18fed8c6e8f1015e809819da9a88dc77de52f0/src/mqtt.c#L1124-L1131


## How to fix
This is actually an easy fix. We only want to include the variable header _iff_ `(publish_flags & 0x06) != 0` (i.e. QoS is not 0). This means that changing lines 1126-1127 to:


```c
1126        if ((publish_flags & 0x06) != 0) {
1127            *(uint16_t*) buf = (uint16_t) MQTT_PAL_HTONS(packet_id);
1128            buf += 2;
1129        }
```

Additionally, the PUBLISH response unpacker (`mqtt_unpack_publish_response` lines 1163-1164) needs to be updated to only unpack PID's if QoS > 0.

```c
1163        if (response->qos_level > 0) {
1116            response->packet_id = (uint16_t) MQTT_PAL_NTOHS(*(uint16_t*) buf);
1165            buf += 2;
1166        }
```

---

Thanks for bringing this up! I will fix this tonight or tomorrow.

Best regards,

Liam

**Comment by jedidiahuang** [comment]
Dear Liam

 

Thank you again for your kindness.

 

I fixed mqtt.c accordingly and got the following error:

1.       From MQTT-fx I published ‘datetime’ 2018/05/10 09:26:00, simple_subscriber received message correctly at the first time

2.       From MQTT-fx I published ‘datetime’ second time, simple_subscriber didn’t respond.

3.       From MQTT-fx I published ‘datetime’ third time, simple_subscriber show 

Received publish(‘’) : ora_MONI  then crash 



4.       simple_publisher published datetime: (pressed <Enter> 3 times)



MQTT-fx received only one incorrect message (see end of message)



 

 

Best Regards,

Jedidiahuang

**Comment by jedidiahuang** [comment]
Hi Liam,

you missed to fix application_message_size in mqtt.c after line 1167

1163        if (response->qos_level > 0) {
1116            response->packet_id = (uint16_t) MQTT_PAL_NTOHS(*(uint16_t*) buf);
1165            buf += 2;
1166        }
1167       
1168        /* get payload */
1169       response->application_message` = buf;
1170       **if ( response->qos_level > 0)**  
1171            response->application_message_size = fixed_header->remaining_length - response->topic_name_size - 4;
1172      else response->application_message_size = fixed_header->remaining_length - response->topic_name_size - **2;**

Now mqtt.c is working very well, Thanks a lot.

Best Regards,
Jedidiahuang

**Comment by jedidiahuang** [comment]
Hi Liam

For mqtt_publish() , there is still have 1 bug code in mqtt.c line 1093
1092      `/* calculate remaining length */`
1093      `remaining_length = __mqtt_packed_cstrlen(topic_name) + 2; /* variable header size */`

This bug will cause an error: MQTT_ERROR_SOCKET_ERROR if publishing QoS 0 topic.

I corrected line 1093 as below, and it works well now
1093     `remaining_length = __mqtt_packed_cstrlen(topic_name);`
1094    ` if ((publish_flags & 0x06) != 0)  remaining_length +=2;`

Best Regards,
Jedidiahuang

**Comment by LiamBindle** [comment]
Hi Jedidiahuang,

Oh right, thanks, I forgot both of those will need to be updated.

Do you want to make a pull request with the updates? If not, I can implement those changes this weekend.

Liam
