### ISSUE TITLE
FreeRTOS?

### ISSUE THREAD

**Issue by edbek** [LiamBindle/MQTT-C#80]
It would be great if your project would be ported to FreeRTOS!

**Comment by LiamBindle** [comment]
I know some people are using MQTT-C with FreeRTOS! IIUC STMicrocontrollers are using FreeRTOS + MQTT-C in X-CUBE-CELLULAR, and NXP is using FreeRTOS + MQTT-C for AN12805. 

MQTT-C isn't mean't to be an out-of-the-box solution; instead, it's meant to be easily ported to your platform. You might be able to find a fork with a FreeRTOS PAL though. If not, implementing your own shouldn't be too much work and I'm happy to answer question on the GH issues. 

If anyone's aware of any open source FreeRTOS PALs, please post it here.
