### ISSUE TITLE
MQTT C embedded server?

### ISSUE THREAD

**Issue by edbek** [LiamBindle/MQTT-C#81]
It was absolutely wonderful if the portable MQTT C server for embedded systems still appeared!

**Comment by LiamBindle** [comment]
@edbek That would be great! IIUC MQTT brokers requirements are quite a bit more than the client, so I'd imagine it would interesting challenge. That being said, I think this is outside the scope of MQTT-C. If anyone knows of any good MQTT broker's that are practical in embedded system, please post it here!

**Comment by edbek** [comment]
https://github.com/martin-ger/uMQTTBroker
