### ISSUE TITLE
Move existing MQTT PAL to templates

### ISSUE THREAD

**Issue by vpetrigo** [LiamBindle/MQTT-C#89]
Hello,

Thank you for your library. I switched to it after I faced some issues with Paho MQTT Embedded C library causing Azure IoT Hub Server Internal error. It has passed several days and no such an error with your library. 👍 

I have a proposal to move a `mqtt_pal.c` and `mqtt_pal.h` from theirs current locations (`src/` and `include/` respectively) to the `examples/templates`. Basically, I would like to add `MQTT-C` library as a git submodule to my project and provide PAL files manually as that allows us to switch to a newer release as it is available by simply switching a tag in the Git tree.

The current PAL still may be built with the library as it is. To allow providing a custom header the following approach may be used:

- **mqtt.c**:
```c
// ...
#if !defined(MQTTC_PAL_FILE)
#include "mqtt_pal.h"
#else
#include MQTTC_PAL_FILE
#endif
// ...
```

And in a side project someone would specify the following (CMake example):
```cmake
add_library(mqttc mqttc/src/mqttc <path/to/mqtt_pal/source>)
target_compile_definitions(mqttc MQTTC_PAL_FILE=my_mqtt_pal.h)
```

That way we will be able to preserve current `mqtt_pal.h` implementation and allow an user to specify theirs own PAL implementation without dealing with manual `mqtt_pal.h` editing in the MQTT-C source tree.

Let me know about your thoughts on that. If you do not mind, I can elaborate on that change and prepare a PR.

**Comment by LiamBindle** [comment]
@vpetrigo That's great! I'm glad it's working well for you. 

I see what you mean. I'm a bit hesitant to move the PAL to the tempalte directory though--I feel like it might be harder for new users to understand which files need to be compiled for MQTT-C. I kind of like the approach that you're currently using though--what do you think of merging that in instead?

**Comment by vpetrigo** [comment]
Hey @LiamBindle,

Sure, I'm not insisting on moving MQTT PAL to templates. 😄 To confirm: would you like me to introduce changes regarding adding an optional compilation flag that allows custom MQTT PAL header include into the main `mqtt.h/mqtt.c` file?
