### ISSUE TITLE
In order delivery not guaranteed for for QoS 2

### ISSUE THREAD

**Issue by LiamBindle** [LiamBindle/MQTT-C#9]
Currently, MQTT-C does not guarantee to PUBLISH messages QoS 2 to the broker in order. This should be supported and should be pretty easy.

See [this thread](https://stackoverflow.com/questions/30955110/is-message-order-preserved-in-mqtt-messages) for a discussion delivery order.

In `__mqtt_send` we should add a flag, `inflight_qos2`, to indicate that a QoS 2 message is inflight to the broker. Then if `inflight_qos2` is set, `resend` should be set to 0 for all subsequent QoS 2 PUBLISH messages. This can be implemented in the following section.

https://github.com/LiamBindle/MQTT-C/blob/5e18fed8c6e8f1015e809819da9a88dc77de52f0/src/mqtt.c#L370-L388

On line 370 we should initialize `inflight_qos2 = 0`. Then on line 384 add the following block:

```c
384         if (msg->control_type == MQTT_CONTROL_PUBLISH &&
385             (msg->state == MQTT_QUEUED_UNSENT || 
386              msg->state == MQTT_QUEUED_AWAITING_ACK)) {
387             inspected = 0x03 & ((msg->start[0]) >> 1); /* qos */
388             if (inspected == 2) {
389                 if (inflight_qos2) resend = 0; /* stop a subsequent QoS 2 from sending */
390                 inflight_qos2 = 1; /* indicate that any subsequent QoS 2 should not be sent */
391             }
392         }
```

I will add this when I have some time this weekend (this, or something close to this should work in the mean time).

**Comment by LiamBindle** [comment]
@amasmiller packet ordering should be correct now.

Regards,

Liam

**Comment by amasmiller** [comment]
Thanks!  I'll give it a try.
