### ISSUE TITLE
Rename MQTT-C main header file

### ISSUE THREAD

**Issue by vpetrigo** [LiamBindle/MQTT-C#90]
Hello,

Another proposal from my side – rename main header file from `mqtt.h` as some embedded systems TCP/IP stack implementations (e.g. [lwip source tree][lwip]) already have `mqtt.h` header in it that leads to improper header file resolution. It may be workarouned by setting up include directories search path in a proper way, but that requires some additional action from an user of MQTT-C library

My proposal:
- rename `mqtt.h` to `mqttc.h`

If you want, I will prepare a PR for that change.

[lwip]: https://github.com/ARMmbed/lwip/tree/master/src/include/lwip/apps

**Comment by LiamBindle** [comment]
@vpetrigo Thanks for the suggestion. I don't have any problem with this, so I'd be happy to merge a PR with this update :smile:

**Comment by yamt** [comment]
@vpetrigo 
lwip seems to have even conflicting symbols eg. mqtt_publish.
isn't it a problem for you?
just curious.

**Comment by vpetrigo** [comment]
Hello @yamt,

No, it is not as long as you do not link lwip's MQTT client implementation altogether with MQTT-C. I can hardly imagine the case when several _different_ MQTT client implementations may be required in a single project. So, no, I do not see an issue with current public interface naming. 😄

**Comment by LiamBindle** [comment]
Closed, see #96. Feel free to reopen if you'd like to discuss further.
