### ISSUE TITLE
Cannot have message size larger than 110 000 bytes

### ISSUE THREAD

**Issue by vrAaF7** [LiamBindle/MQTT-C#92]
I have modified simple_publisher.c to read local file and deliver file content over mqtt channel. However I cannot exceed ~110 000 byte limit (even maximum of MQTT is way bigger).  

I have used mosquitto_pub & mosquitto_sub to verify that my broker allows bigger payload delivery. 

Is there something I am missing here ?

**Comment by LiamBindle** [comment]
@vrAaF7 Are you using a recent version of MQTT-C? https://github.com/LiamBindle/MQTT-C/pull/83 fixed a bug that was breaking messages larger than 64 KB.

**Comment by LiamBindle** [comment]
I believe this is fixed in #83. Feel free to reopen if I've misunderstood.
